RM2MS11-28update
RM2PT/RM2PT.github.io pull request #36
Opened 2022-11-28 10:16 UTC by liyang1206

add some images and rm2ms.md
change rm2ms-toturial.md

2022-11-28 17:16 UTC, yylonly commented on page/rm2ms/rm2ms-tutorial.md
> +   <img title="" src="..\..\imgs\RM2MS\overview.jpg" alt="">
move to tutorail section

2022-11-28 17:17 UTC, yylonly commented on page/rm2ms/rm2ms-tutorial.md
>  ## Use of RM2MS
RM2MS Tutorail

2022-11-28 17:21 UTC, yylonly commented on page/rm2ms/rm2ms-tutorial.md
> +   <img title="" src="..\..\imgs\RM2MS\overview.jpg" alt="">
Move to Tutorial Section

2022-11-28 17:26 UTC, yylonly commented on page/rm2ms/rm2ms-tutorial.md
> +   <img title="" src="..\..\imgs\RM2MS\overview.jpg" alt="">
Move img to Tutorial Section

2022-11-28 17:26 UTC, yylonly commented on page/rm2ms/rm2ms-tutorial.md
>  ## Use of RM2MS
Change "Use of RM2MS" to "RM2MS Tutorail"

2022-11-28 17:26 UTC, yylonly commented on page/rm2ms/rm2ms-tutorial.md
Put overview image here

2022-11-28 17:27 UTC, yylonly reviewed
modify .md as marked in thre view

2022-11-28 17:27 UTC, yylonly reviewed
modify .md as marked in thre view

2022-11-28 17:27 UTC, yylonly reviewed
modify .md as marked in thre view

2022-11-28 17:27 UTC, yylonly reviewed
modify .md as marked in thre view

2022-11-28 17:30 UTC, yylonly requested changes
modify .md as marked in thre view

2022-11-29 03:39 UTC, liyang1206 commented
modification

2022-11-29 10:43 UTC, liyang1206 commented
modification

2022-11-29 10:44 UTC, liyang1206 commented
I hava modifided

2022-11-30 07:16 UTC, merged